In [58]:
import tensorflow as tf






    #heights = tf.cast(tf.math.round(true), tf.int32)

    #return tf.reduce_mean(-tf.reduce_sum(tf.gather(pred, indices,  )

layer_ce(true, pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7.9214387, 7.9214387], dtype=float32)>

In [56]:
import tensorflow as tf
true = tf.tile(tf.expand_dims(tf.tile(tf.expand_dims(tf.range(10), 1), multiples=[1, 5]), 0), [2, 1,1])
pred = tf.tile(tf.expand_dims(tf.range(10), 1), [1,10])
pred = tf.tile(tf.expand_dims(tf.tile(tf.expand_dims(pred, -1) , [1,1,5]), 0), [2,1,1,1]) / 10

In [42]:
x_indices = tf.reshape(tf.range(true.shape[1]), (1,10,1))
x_indices = tf.tile(x_indices, (2,1,5))

indices = tf.stack([true, x_indices], axis=1)

In [43]:
indices

<tf.Tensor: shape=(2, 2, 10, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8],
         [9, 9, 9, 9, 9]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8],
         [9, 9, 9, 9, 9]]],


       [[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8],
         [9, 9, 9, 9, 9]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5],
   

In [47]:
tf.gather_nd(pred, [[[[0,5,5,0]]]])

<tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[5]]], dtype=int32)>